# Generated by Django 3.0.4 on 2020-03-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200312_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avilb',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=100),
        ),
    ]
