# Generated by Django 3.0.4 on 2020-03-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200312_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avilb',
            new_name='discount',
        ),
    ]
